### ISSUE TITLE
BART backbone

### ISSUE THREAD

**Issue by GMago123** [Jacob-Zhou/gecdi#1]
Hello，在论文B.3 Tricks的MuCGEC部分，我注意到您提到了"employ the same fnlp/bart-large-chinese"，这是否也意味着SynGEC方法里面对词表进行附加的操作是否也得到了保留？SynGEC的论文第5部分”Use of BART“一节提到了词表中添加了3866个汉字和标点符号。

**Comment by Jacob-Zhou** [comment]
您好，我们用的是复旦那边更新后的bart。他们已经更新了词表，因此我们并没有进行词表附加操作。

发自我的 iPhone

在 2023年11月16日，10:16，Wei Li ***@***.***> 写道：

﻿

Hello，在论文B.3 Tricks的MuCGEC部分，我注意到您提到了"employ the same fnlp/bart-large-chinese"，这是否也意味着SynGEC方法里面对词表进行附加的操作是否也得到了保留？SynGEC的论文第5部分”Use of BART“一节提到了词表中添加了3866个汉字和标点符号。

**Comment by GMago123** [comment]
MuCGEC文章里Seq2Seq单模型在MuCGEC测试集上的最高F0.5结果是39.39，本篇文章里46.88，训练配置我看两篇文章是差不多的，所以新的BART模型带了了7个点的提升吗？

**Comment by GMago123** [comment]
不好意思看成dev的结果了，表格2显示test的结果是47.41，相当于带来了8个点的提升？

**Comment by Jacob-Zhou** [comment]
因为参考的是 SynGec 的做法，所以 baseline 的提升应该是 45.93→47.41。只有 1.48。

**Comment by Jacob-Zhou** [comment]
在 MuCGEC 中的附录 C 中有提到一个 trick。但是他们并没有实际用上，我们和 SynGEC 都用了。

We find this trick can con- sistently improve performance in our preliminary experiments. For now, we decide not to break the sentences when releasing in order to be consistent with the sources where the data comes from.

就是会把句子按句话、问号等分开进行预测，预测完成后再拼接。
这个带来的提升还挺大的，但是具体多少我忘记了，你可以尝试一下。

**Comment by Jacob-Zhou** [comment]
还有个训练细节，我不清楚 SynGEC 里面有没有提到：他们在训练的时候用的是 Lang8 数据集 + HSK 数据集，其中的 HSK 数据集会通过复制 5 次的方式来增大其在总体数据中占比。

**Comment by GMago123** [comment]
> 因为参考的是 SynGec 的做法，所以 baseline 的提升应该是 45.93→47.41。只有 1.48。

不好意思，还是没太理解你的”参考“指的是什么，这个45.93是原来的BART加了词表（~3866个）后模型的结果，但是您说没有再补充词表，只是用了新的BART

**Comment by Jacob-Zhou** [comment]
我的训练数据的配比以及预测trick是和SynGEC 一致的。而他们向BART中加词表的原因是原始的中文 BART 缺失了很多常用字以及常见标点 (会导致一些标点和字无法被预测)，这个在后续的BART版本中被修复了，因此也就没有必要像 SynGEC 那样添加词表了。

**Comment by Jacob-Zhou** [comment]
对不起，之前太忙看漏对话了。

    新的BART模型带了了7个点的提升吗

新的BART模型确实带来的提高还是蛮大的，不过应该没到 8 个点，里面还有 1) 按结束标点截断，和 2) 长度阈值这俩因素的影响。

新的BART模型的主要解决了之前版本中常见字以及标点的缺失问题。因为缺失的话这些字就没法被正确预测出来。

**Comment by GMago123** [comment]
> 对不起，之前太忙看漏对话了。
> 
> ```
> 新的BART模型带了了7个点的提升吗
> ```
> 
> 新的BART模型确实带来的提高还是蛮大的，不过应该没到 8 个点，里面还有 1) 按结束标点截断，和 2) 长度阈值这俩因素的影响。
> 
> 新的BART模型的主要解决了之前版本中常见字以及标点的缺失问题。因为缺失的话这些字就没法被正确预测出来。
> 
> PS: 刚才试了一下，如果没有用上面提到的两个 tricks 的话，新 BART 的结果是 43.67, 提升只有 4.28

好的，大致的情况了解了，十分感谢！
