### ISSUE TITLE
请教下target 包含多个候选如何处理

### ISSUE THREAD

**Issue by canghaiyunfan** [Jacob-Zhou/gecdi#5]
如果一个病句包含多种改法，训练和验证数据应该怎么处理

**Comment by Jacob-Zhou** [comment]
您好，在本工作中如果遇到“一个病句包含多种改法”的情况，我们是直接将不同的改法作为不同的样例放在数据集中。
即，如果 X 有 A、 B、C 这三种改法那么在训练集和验证集中应该是如下这样：

> S \t X
> T \t A
>
> S \t X
> T \t B
>
> S \t X
> T \t C

但这并不是最好的方法，如何充分利用包含多种改法的样例可以被归结为多参考训练问题。目前有些工作在进行这方面的研究。
例如，您可以参考这篇文章([Focus Is What You Need For Chinese Grammatical Error Correction](https://arxiv.org/pdf/2210.12692.pdf))了解目前多参考纠错的做法。 

在这篇文章中，作者尝试利用 Levenshtein ratio、Jaccard similarity 和编辑距离来从多种改法中选取最优的改法。从他们论文中给出的结果来看，选取 Levenshtein ratio 最为接近的改法进行训练，是最好的做法。

**Comment by canghaiyunfan** [comment]
明白，感谢回答

**Comment by canghaiyunfan** [comment]
训练集这样处理可以理解，但验证集这样处理的话是不是有问题，如果有1000 条验证集，部分数据包含多个参考答案，按照上面的方法展开验证集数量肯定大于1000， 这样转成m2 文件计算F0.5 是不是对不上？

**Comment by canghaiyunfan** [comment]
明白，感谢作者详细的解答
